Meruemshop/Meruem_shop/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import RedirectView
from Meruem_shop.views import homepage_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', homepage_view),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cases/', include('phone_case.urls')),
    path('admin/', admin.site.urls),
    path('contact_data/', include('contact.urls')),
    path('contact/', include('contact.urls')),
    path('success/', include('contact.urls')),
    path('buy/', include('phone_case.urls')),
    path('successbuy/', include('phone_case.urls')),
    path("favico.ico/", RedirectView.as_view(url=staticfiles_storage.url("favico.ico"))),
]

if settings.DEBUG is True:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Meruemshop/contact/urls.py
from django.contrib import admin
from django.urls import path

from .views import contactView, successView, contactsView
from contact import views

app_name = 'contact'

urlpatterns = [
    path('contact_data', contactsView, name='contact_data'),
    path('contact', contactView, name='contact'),
    path('success', successView, name='success'),
]

Meruemshop/phone_case/urls.py
from django.urls import path
from phone_case import views

app_name = 'phone_case'

urlpatterns = [
    path('', views.CasesView.as_view(), name='lista_cases'),
    path('adaugare/', views.CreateCaseView.as_view(), name='adauga'),
    path('modificare/<int:pk>/', views.UpdateCaseView.as_view(), name='modifica'),
    path('sterge/<int:pk>/', views.deactivate_case, name='dezactiveaza'),
    path('buy/<int:pk>/', views.buycartView, name='buy'),
    path('successbuycase/<int:pk>/', views.updatequantityview, name='successbuycase'),
]

Meruemshop/users/urls.py

from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('upload', views.upload_view, name='upload'),
    path('profile', views.profile_view, name='profile'),
]

Meruemshop/templates/base.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'favico.ico' %}"/>
</head>
<body>
{% include 'menu.html' %}
{% block content %}
{% endblock %}
</body>
</html>

Meruemshop/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Meruem's Shop</title>
{% endblock %}

{% block content %}
<h1 align="center">
    {{ title }}
</h1>
<h1 align="center">
    <img src="{% static 'images/phone_case.jpg' %}" class="rounded-circle" alt="Phone Case" width="200"/>
</h1>
<div>
{% if request.user.is_authenticated %}
    <p align="center">Hi, welcome to our page!</p>
    <p align="center">If you are trying to find a case for your phone you can take a look <a
            href="http://127.0.0.1:8000/cases/" id="link">here.</a></p>
{% else %}
    <p align="center">Hi, welcome to our page!</p>
    <p align="center">If you are new, please create an account by pressing <a href="http://127.0.0.1:8000/users/register" id="link">here.</a></p>
{% endif %}
</div>
{% endblock %}

Meruemshop/templates/menu.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='https://fonts.googleapis.com/css?family=Cinzel Decorative' rel='stylesheet'>
<style>

body {
    font-family: 'Optima';font-size: 22px;
}

/* Menu */
.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  opacity: 0.9;
  overflow-x: hidden;
  padding-top: 60px;
  transition: 0.5s;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 20px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div align="center">
<span onclick='openNav()'> <button type="button" class="block">Menu</button></span>
</div>

<script>

function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
    document.body.style.backgroundColor = "white";
}
</script>

<div id="mySidenav" class="sidenav">
<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    {% if request.user.is_authenticated %}
        <div>
        {% elif request.user.is_authenticated and request.user.is_superuser %}
            <div>
            {% endif %}
                <a class="active" href="/">Homepage</a>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_authenticated and request.user.is_superuser %}
                        <a class="active" href="/admin">Admin</a>
                    {% endif %}
                    <a class="active" href="{% url 'phone_case:lista_cases' %}">Cases</a>
                    <a class="active" href="{% url 'users:profile' %}">Profile of {{ request.user.first_name }} {{ request.user.last_name }}</a>
                    <a class="active" href="{% url 'users:logout' %}">Logout</a>
                    <a class="active" href="{% url 'contact:contact_data' %}">Contact</a>
                {% else %}
                    <a class="active" href="{% url 'users:login' %}">Login</a>
                    <a class="active" href="{% url 'users:register' %}">Register</a>
                    <a class="active" href="{% url 'contact:contact_data' %}">Contact</a>
                {% endif %}
        </div>
    </div>
</div>
</body>
</html>