proiect/first_app1/urls.py
from django.urls import path
from first_app1 import views

app_name = 'companies'

urlpatterns = [
    path('adaugare/', views.CreateCompanyView.as_view(), name='add'),
    path('', views.CompanyView.as_view(), name='list'),
    path('<int:pk>/delete', views.delete_company, name='delete'),
    path('<int:pk>/update', views.UpdateCompanyView.as_view(), name='modify'),
    path('<int:pk>/activate', views.activate_company, name='activate'),
    path('inactive_companies', views.CompanyInactiveView.as_view(), name='inactive'),
]

proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers
from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('first_app.urls')),
    path('companies/', include('first_app1.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/', include('myapi.urls'))

]

proiect/first_app1/models.py
from django.db import models

from first_app.models import Location


class Companies(models.Model):
    company_choices = (('SRL', 'S.R.L.'),
                       ('SA', 'S.A.'))

    name = models.CharField(max_length=100)
    website = models.CharField(max_length=50)
    company_type = models.CharField(max_length=5, choices=company_choices)
    active = models.BooleanField(default=1)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.company_type} {self.name}"

proiect/first_app1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from first_app1.models import Companies


class CompanyView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'first_app1/company_index.html'
    paginate_by = 5
    queryset = model.objects.filter(active=1)
    context_object_name = 'companies'

    def get_context_data(self, *args, **kwargs):
        data = super(CompanyView, self).get_context_data()
        # data['companies_list'] = self.model.objects.filter(active=1)
        return data


class CreateCompanyView(LoginRequiredMixin, CreateView):
    model = Companies
    fields = ['name', 'website', 'company_type', 'active']
    template_name = 'first_app1/company_form.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


class UpdateCompanyView(LoginRequiredMixin, UpdateView):
    model = Companies
    fields = ['name', 'website', 'company_type', 'active']
    template_name = 'first_app1/company_form.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


@login_required
def delete_company(request, pk):
    Companies.objects.filter(id=pk).update(active=0)
    return redirect('companies:lista_companii')


@login_required
def activate_company(request, pk):
    Companies.objects.filter(id=pk).update(active=1)
    return redirect('companies:lista_companii')


class CompanyInactiveView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'first_app1/company_index.html'
    paginate_by = 5
    queryset = model.objects.filter(active=0)
    context_object_name = 'companies'

    def get_context_data(self, *args, **kwargs):
        data=super(CompanyInactiveView, self).get_context_data(*args, **kwargs)
        # data['companies_list'] = self.model.objects.filter(active=0)
        return data

proiect/templates/first_app1/company_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

proiect/templates/first_app1/company_index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <a class="btn btn-primary" href="{% url 'companies:add' %}">Add a company</a>
        <table class="table">
            <thead>
            <tr>
                <th>Index</th>
                <th>Company</th>
                <th>Website</th>
                <th>Type</th>
                <th>State</th>
            </tr>
            </thead>
            <tbody>
            {% for item in companies_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.website }}</td>
                    <td>{{ item.company_type }}</td>
                    <td>
                        {% if item.active == 1 %}
                            <span>Activ</span>
                        {% else %}
                            <span>Inactiv</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'companies:modify' item.id %}" class="btn btn-success">Modify</a>
                        {% if item.active == 1 %}
                            <a href="{% url 'companies:delete' item.id %}" class="btn btn-danger">Delete</a>
                        {% else %}
                            <a href="{% url 'companies:activate' item.id %}" class="btn btn-info">Activate</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
            {% else %}
                <li class="disabled btn"><span><<</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                {% else %}
                    <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
            {% else %}
                <li class="disabled btn"><span>>></span></li>
            {% endif %}
            <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
                {{ page_obj.paginator.count }}</span>
        </ul>
    {% endif %}
{% endblock %}